"""
Written by Collin Hoffman,some functions are modified from the below document.

4/7/2022 as part of Dr. Gang Shao's research.

bag_of_words_matrix.py

Original Credits:

Intro_To_NLP_Part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_eYHgw8JM3RyPT9NCyyczDaJRojyrHj

Author: Vishnu Teja Narapareddy

E-mail: vnarapar@purdue.edu

Date: September 27th 2021

# Intro to Natural Language Processing Part 1
"""

import nltk
from sklearn.feature_extraction.text import CountVectorizer

#import pandas
import pandas as pd


#these tags are already cleaned, take only tags column
tags_df = pd.read_csv('Cleaned_abstract_tags(1).csv', usecols = ['Tags'])

#initialize vectorizer as function
vectorizer = CountVectorizer()

#create a list from dataframe
tags_list = tags_df.values.tolist()

#define a new list
new_list = []

#convert tag phrases to a snakecase

#tags_list is a list of lists, and each "sentences" is a string of tags

new_sentence = []
for sentences in tags_list:
    
    
    
    #words are all strings in the sentence
    for words in sentences:
        
        #split the string into a list, where each tag is an element of word_list
        word_list = words.split(",")
        
        new_words = []
        
        #for each tag in the tags of the document, strip whitespace and replace 
        #other whitespace with "_"
        for word in word_list:
            word = word.strip()
            word = word.replace(" ", "_")

            new_words.append(word)
        new_sentence.append(new_words)

#new_sentence is a list of lists, where each sublist are all the tags of a document

#need to convert sublists in new_lists to strings
        


#for each list in tags_list, join the list together
newer_list = []
for sentence in new_sentence:
    
    final_sen = " ".join(sentence)
   
    newer_list.append(final_sen)
        

#now have a list of strings in new_list

#create a matrix by transforming/vectorizing new_list
matrix = vectorizer.fit_transform(newer_list)

#perform matrix multiplication
matrix_end = matrix.T * matrix

#set the columns of the dataframe to the feature names
names = vectorizer.get_feature_names()
#turn matrix to an array to a dataframe
df = pd.DataFrame(matrix_end.toarray(), columns = names, index = names)




#export to a csv
df.to_csv('bag_of_words(1).csv')


